# Default values for admin-portal-web-ui
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: casablanca-casa-docker-release.jfrog.io/admin-portal-web-ui
  tag: 9.5.1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

imageCredentials:
  name: dock-casa-secret

ingress:
  enabled: true
  externalPath: /
  # Used to create an Ingress record.
  hosts:
    api: admin-portal-web-ui.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: '/'
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
