apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "admin-portal-web-ui.fullname" . }}
  labels:
    app: {{ template "admin-portal-web-ui.name" . }}
    chart: {{ template "admin-portal-web-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "admin-portal-web-ui.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "admin-portal-web-ui.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
      imagePullSecrets:
      - name: {{ .Values.imageCredentials.name }}
